// designer-save.js — shared panel-editor save logic.
//
// Used by both the in-app IPC handler (electron-main) and the standalone dev server
// (designer-server). Writes a module's files and regenerates its panels. CommonJS so
// electron-main can require it; designer-server imports its default. gen-panel is run
// through our own binary — plain Node in the dev server, Electron-as-Node in the app
// (ELECTRON_RUN_AS_NODE is ignored by real Node, so one code path serves both).
'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { execFile } = require('node:child_process');

const MODULE_DIRS = new Set(['complex-oscillator-259t', 'lpg-292', 'function-gen-281t', 'mixer', 'gallery']);
const SAFE_DIR = /^[a-z0-9][a-z0-9-]*$/;

// List every module folder under modules/. `authored` = generated by the editor (its
// descriptor carries the GENERATED header), which is how the editor knows it fully owns
// the module and may reopen it editable. `shipped` = one of the official built-ins.
const { pathToFileURL } = require('node:url');

function listModules(root) {
  const base = path.join(root, 'modules');
  const out = [];
  let names = [];
  try { names = fs.readdirSync(base); } catch (_e) { return out; }
  for (const name of names) {
    const modDir = path.join(base, name);
    try { if (!fs.statSync(modDir).isDirectory()) continue; } catch (_e) { continue; }
    const descPath = path.join(modDir, 'descriptor.js');
    if (!fs.existsSync(descPath) || !fs.existsSync(path.join(modDir, 'panel.layout.js'))) continue;
    let authored = false;
    try { authored = fs.readFileSync(descPath, 'utf8').includes('GENERATED by the panel editor'); } catch (_e) { /* unreadable */ }
    out.push({ dir: name, authored, shipped: MODULE_DIRS.has(name) });
  }
  return out;
}

const GEN_TEMPLATE = `// Generated by the panel editor. Renders panel.layout.js to the light + dark SVGs
// via the shared renderer, applying panel.overrides.json if present.
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import { renderPanel } from '../../panel/render.js';
import { applyOverrides } from '../../panel/overrides.js';
import layout from './panel.layout.js';

const dir = fileURLToPath(new URL('.', import.meta.url));
const ovPath = dir + 'panel.overrides.json';
if (fs.existsSync(ovPath)) applyOverrides(layout, JSON.parse(fs.readFileSync(ovPath, 'utf8')));
fs.writeFileSync(dir + 'panel.svg', renderPanel(layout, false));
fs.writeFileSync(dir + 'panel.dark.svg', renderPanel(layout, true));
console.log('wrote panel.svg + panel.dark.svg');
`;

const DESC_HEADER = `// descriptor.js — GENERATED by the panel editor from the drawn interface.
// The module's ports and params fall out of the drawing; edit them in the editor,
// not here. The factory (hand-written) implements behaviour against these ids.

`;

function regen(root, modDir) {
  return new Promise((resolve, reject) => {
    execFile(process.execPath, [path.join(modDir, 'gen-panel.js')],
      { cwd: root, env: { ...process.env, ELECTRON_RUN_AS_NODE: '1' } },
      (err, _o, stderr) => (err ? reject(new Error(String(stderr || err))) : resolve()));
  });
}

// IS THIS MODULE'S LAYOUT STILL THE TRUTH? Renders panel.layout.js (plus its overrides) and compares
// with the panel.svg on disk. They agree for every module today; the reason to keep asking is what
// happens when they stop. A hand-edit to a shipped SVG leaves the layout describing something else —
// the editor then draws the layout, which is not the panel you have, and a save regenerates from it,
// quietly replacing the artwork with a picture nobody chose. That is exactly how the function
// generator drifted, and it went unnoticed for a long time because nothing ever asked.
//
// Renders in a child process, since the renderer is an ES module and this file is CommonJS.
function panelInSync(root, dir) {
  const modDir = path.join(root, 'modules', dir);
  const svgPath = path.join(modDir, 'panel.svg');
  if (!fs.existsSync(svgPath) || !fs.existsSync(path.join(modDir, 'panel.layout.js'))) return Promise.resolve(null);
  const src = `
    import fs from 'node:fs';
    import { renderPanel } from ${JSON.stringify(pathToFileURL(path.join(root, 'panel', 'render.js')).href)};
    import { applyOverrides } from ${JSON.stringify(pathToFileURL(path.join(root, 'panel', 'overrides.js')).href)};
    const layout = (await import(${JSON.stringify(pathToFileURL(path.join(modDir, 'panel.layout.js')).href)})).default;
    const ov = ${JSON.stringify(path.join(modDir, 'panel.overrides.json'))};
    if (fs.existsSync(ov)) applyOverrides(layout, JSON.parse(fs.readFileSync(ov, 'utf8')));
    process.stdout.write(renderPanel(layout, false));
  `;
  return new Promise((resolve) => {
    execFile(process.execPath, ['--input-type=module', '-e', src],
      { cwd: root, maxBuffer: 32 * 1024 * 1024, env: { ...process.env, ELECTRON_RUN_AS_NODE: '1' } },
      (err, out) => {
        if (err) return resolve(null);   // cannot tell — do not block on a failure to check
        try { resolve(out === fs.readFileSync(svgPath, 'utf8')); } catch (_e) { resolve(null); }
      });
  });
}

// Two save shapes, mirroring the editor:
//   { dir, overrides }                        -> shipped module: write overrides, regen SVGs
//   { dir, editorOwned, layout, descriptor }  -> authored module: write layout + generated
//                                                descriptor + gen-panel, regen SVGs
// Returns { ok, ... } or { error }.
async function savePanel(root, msg) {
  const dir = msg && msg.dir;
  try {
    if (msg && msg.editorOwned) {
      if (!SAFE_DIR.test(dir || '')) return { error: `unsafe module dir "${dir}"` };
      if (!msg.layout || !msg.descriptor) return { error: 'missing layout/descriptor' };
      const modDir = path.join(root, 'modules', dir);
      if (!modDir.startsWith(path.join(root, 'modules') + path.sep)) return { error: 'bad path' };
      fs.mkdirSync(modDir, { recursive: true });
      fs.writeFileSync(path.join(modDir, 'panel.layout.js'), 'export default ' + JSON.stringify(msg.layout, null, 2) + ';\n');
      fs.writeFileSync(path.join(modDir, 'descriptor.js'), DESC_HEADER + 'export default ' + JSON.stringify(msg.descriptor, null, 2) + ';\n');
      fs.writeFileSync(path.join(modDir, 'gen-panel.js'), GEN_TEMPLATE);
      await regen(root, modDir);
      return { ok: true, dir };
    }
    if (!MODULE_DIRS.has(dir)) return { error: `unknown module "${dir}"` };
    // Saving a shipped module regenerates its SVGs from its layout. If the two have drifted apart,
    // that save does not adjust the panel you are looking at — it replaces it.
    if (await panelInSync(root, dir) === false) {
      return { error: `"${dir}" cannot be saved: its panel.layout.js no longer reproduces its `
        + 'panel.svg, so saving would overwrite the shipped faceplate with a different drawing. '
        + 'Resync the layout to the SVG first.' };
    }
    const overrides = msg.overrides;
    if (!overrides || typeof overrides !== 'object') return { error: 'no overrides' };
    const modDir = path.join(root, 'modules', dir);
    const ovPath = path.join(modDir, 'panel.overrides.json');
    if (Object.keys(overrides).length) fs.writeFileSync(ovPath, JSON.stringify(overrides, null, 2) + '\n');
    else if (fs.existsSync(ovPath)) fs.unlinkSync(ovPath);   // empty = back to the pristine layout
    await regen(root, modDir);
    return { ok: true, overrides };
  } catch (e) {
    return { error: String((e && e.message) || e) };
  }
}

module.exports = { savePanel, listModules, panelInSync };
